import Head from 'next/head'
import styles from "../styles/Dog.module.scss";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Find My Dog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Image
          src="/logo.png"
          alt="Picture of app logo"
          width={300}
          height={300}
          style={{ cursor: "pointer" }}
        />
        <h1>Find My Dog</h1>
        <p className={styles.indexText}>A mobile app for reporting stolen, lost and found dogs. Create posts and send notifications to near by users to look out for dogs or notifications to potential owners of a found dog. Live chat with each other to keep in contact, print or share posts. All in the Find my dog app!</p>
      </main>
    </div>
  )
}